global:
  scrape_interval:     10s
  external_labels:
    monitor: hello-observability

scrape_configs:
  - job_name: loki
    scrape_interval: 10s
    static_configs:
      - targets: [loki:3100]

  - job_name: tempo
    scrape_interval: 10s
    static_configs:
      - targets: [tempo:3200]

  - job_name: nginx
    static_configs:
    - targets: ['nginx-exporter:9113']

  - job_name: actuator
    metrics_path: /actuator/prometheus
    static_configs:
    - targets: ['hello-observability:8080']